name: Deploy Frontend to GitHub Pages

on:
  schedule:
    - cron: "0 */3 * * *" # Runs every 3 hours
  push:
    branches:
      - LSTM_station

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: temp_normals

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Consider using a variable for Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: temp_normals/build
